  
tasks:
  - name: pip install graphviz & Diagram
    init: |
      pip install graphviz
      pip install diagrams
      sudo apt-get update
      sudo apt install graphviz
      # sudo apt install xdg-utils
      # sudo apt-get install xdg-utils --fix-missing
      alias xdg-open="gp open"
      gp sync-done installs
      echo "installation finished"
      echo "try to run as follows or test other recipes $ python example.py"
    
  - name: install check
    init: |
      gp sync-await installs
      dot -V
      #xdg-open --help     
    openMode: split-right

# Ports to expose on workspace startup
# ports:
#   - port: 8080
#     onOpen: open-preview