  
tasks:
  - name: pip install graphviz & Diagram
    init: |
      pip install graphviz
      pip install diagrams
      sudo apt install graphviz
      sudo apt-get install xdg-utils --fix-missing
      
  - name: install check
    init: |
      dot -V
      xdg-open --help    openMode: split-right      

# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview